import csv
from typing import Any
import keyboard

#KeyboardEvent.time - results a UNIX timestamp of when the action occurs
#keyboard.record - returns a list containing individual actions sectioned to presses and releases, stops upon a hot key (default to "esc")
#the goal of these two is to combine them to calculate dwell, flight, etc.

#Modularized logger (legit just records key pressed and releases and returns a list of them
def log() -> list[Any]:
    events: list[Any] = keyboard.record() #during data processing, will need to remove last line of each CSV file as that is the exit hotkey.
    return events

#Generates a CSV file (csv file name defaults to 'logged_keys.csv')
#Worthwhile to note that it takes the list generated by log() and starts off adding headers into the file
#Once the headers are added, it iterates through teh list of events and adds a row into the CSV file for each event
def generate_csv(events_: list[Any], filename: str = "data/logged_keys.csv"):
    with open(filename, "a", newline="") as f:
        field_names: list[Any] = ["event", "timestamp"]
        writer: csv.DictWriter[Any] = csv.DictWriter(f, fieldnames=field_names)
        writer.writeheader()
        for event in events_:
            event_str: str = str(event)
            writer.writerow({"event": event_str, "timestamp": event.time})
    print("File Updated")


#Main guard/test of this .py files functions
if __name__ == "__main__":

    logged: list[Any] = log()
    generate_csv(events_=logged)




